CREATE DATABASE LOJA_DE_MUSICA;
GO

USE LOJA_DE_MUSICA;
GO

-- PRODUTO PRIMEIRA FASE:


CREATE TABLE TIPO_PRODUTO (
  ID_TIPO_PRD                       INT IDENTITY(1,1) PRIMARY KEY 
, TIPO_PRD                     VARCHAR (50)          NOT NULL
, NOME_PRD                      VARCHAR (50) UNIQUE	     NOT NULL 
);

CREATE TABLE MARCA_PRODUTO (	
  ID_MARCA_PRD                    INT IDENTITY(1,1) PRIMARY KEY 
, MARCA_PRD                    	   VARCHAR (50)	   UNIQUE NOT NULL
);

CREATE TABLE PRODUTO (
  ID_DESC_PRD              	INT IDENTITY(1,1) PRIMARY KEY 
, COD_BARRAS 				 VARCHAR (100) NOT NULL UNIQUE
, MODELO_PRD 			VARCHAR (50)	    NOT NULL
, COR_PRD                      	VARCHAR (20)	    NOT NULL
, PRECO_PRD                     MONEY		    NOT NULL
, QTD_EM_ESTOQUE_PRD            INT 		    NOT NULL
, ENABLE			BIT 	            NOT NULL
	
, ID_TIPO_PRD INT FOREIGN KEY REFERENCES TIPO_PRODUTO(ID_TIPO_PRD) NOT NULL
, ID_MARCA_PRD INT FOREIGN KEY REFERENCES MARCA_PRODUTO(ID_MARCA_PRD) NOT NULL

, CONSTRAINT UNIQUE_MARCA_PROD_MODEL UNIQUE (ID_TIPO_PRD, ID_MARCA_PRD, MODELO_PRD)
);



-- CLIENTE PRIMEIRA FASE: 

CREATE TABLE ENDERECO_CLIENTE (
  ID_ENDERECO_CLIENTE                  INT PRIMARY KEY IDENTITY
, CEP CHAR (8)
, LOGRADOURO VARCHAR (50)
, NUMERO VARCHAR(8)
, BAIRRO VARCHAR (50)
, CIDADE VARCHAR (50)
, UF CHAR (2)
);

CREATE TABLE CONTATO_CLIENTE(
  ID_CONTATO_CLIENTE                  INT PRIMARY KEY IDENTITY
, TELEFONE CHAR (10)
, CELULAR CHAR (11)
, EMAIL VARCHAR (100)
);

CREATE TABLE CLIENTE (
  ID_CLIENTE                  INT PRIMARY KEY IDENTITY
, NOME_CLIENTE                VARCHAR (200)	 NOT NULL
, CPF_CLIENTE                 CHAR    (20) 	 NOT NULL
, RG_CLIENTE                  CHAR    (20)	 NOT NULL 
, SEXO_CLIENTE                CHAR    (1)	 NOT NULL
, ESTADO_CIVIL_CLIENTE        VARCHAR (30)	 NOT NULL
, DT_NASCIMENTO_CLIENTE       VARCHAR (30)	 NOT NULL
, ENABLE		      BIT                NOT NULL	
, ID_ENDERECO_CLIENTE INT FOREIGN KEY REFERENCES ENDERECO_CLIENTE (ID_ENDERECO_CLIENTE) NOT NULL
, ID_CONTATO_CLIENTE INT FOREIGN KEY REFERENCES CONTATO_CLIENTE (ID_CONTATO_CLIENTE) NOT NULL	
);
