package br.com.senac.lojashowmuscial.userinterface.principal;

import br.com.senac.lojashowmuscial.userinterface.cliente.CadastroClienteUI;
import br.com.senac.lojashowmuscial.userinterface.cliente.ConsultaClienteUI;
import br.com.senac.lojashowmuscial.userinterface.funcionario.CadastroFuncionarioUI;
import br.com.senac.lojashowmuscial.userinterface.produto.CadastroProdutoUI;
import br.com.senac.lojashowmuscial.userinterface.produto.ConsultaProdutoUI;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mattheus.prleite
 */
public class PrincipalUI extends javax.swing.JFrame {

    private CadastroClienteUI cadastrarCliente;
    private ConsultaClienteUI consultarCliente;
    private CadastroProdutoUI cadastrarProduto;
    private ConsultaProdutoUI consultarProduto;
    private CadastroFuncionarioUI cadastrarFuncionario;

    /**
     * Creates new form Menu
     */
    public PrincipalUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel(){
            private Image image;
            {
                try {
                    image = ImageIO.read(new File("src/br/com/senac/lojashowmuscial/userinterface/principal/viola.jpeg"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent (Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadasCliente = new javax.swing.JMenuItem();
        menuConsulCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadasProduto = new javax.swing.JMenuItem();
        menuConsulProduto = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jMenuBar1.setFocusCycleRoot(true);

        jMenu1.setText("Cliente");
        jMenu1.setToolTipText("");

        menuCadasCliente.setText("Cadastrar");
        menuCadasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadasClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadasCliente);

        menuConsulCliente.setText("Consultar");
        menuConsulCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsulClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuConsulCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        menuCadasProduto.setText("Cadastrar");
        menuCadasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadasProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadasProduto);

        menuConsulProduto.setText("Consultar");
        menuConsulProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsulProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsulProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadasClienteActionPerformed
        if (cadastrarCliente == null || !cadastrarCliente.isDisplayable()) {
            cadastrarCliente = new CadastroClienteUI();
            cadastrarCliente.pack();
            cadastrarCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            cadastrarCliente.setLocationRelativeTo(null);
            cadastrarCliente.setVisible(true);
        }
        cadastrarCliente.toFront();
    }//GEN-LAST:event_menuCadasClienteActionPerformed

    private void menuConsulClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsulClienteActionPerformed
        if (consultarCliente == null || !consultarCliente.isDisplayable()) {
            consultarCliente = new ConsultaClienteUI();
            consultarCliente.pack();
            consultarCliente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            consultarCliente.setLocationRelativeTo(null);
            consultarCliente.setVisible(true);
        }
        consultarCliente.toFront();
    }//GEN-LAST:event_menuConsulClienteActionPerformed

    private void menuCadasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadasProdutoActionPerformed
        if (cadastrarProduto == null || !cadastrarProduto.isDisplayable()) {
            cadastrarProduto = new CadastroProdutoUI();
            cadastrarProduto.pack();
            cadastrarProduto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            cadastrarProduto.setLocationRelativeTo(null);
            cadastrarProduto.setVisible(true);
        }
        cadastrarProduto.toFront();
    }//GEN-LAST:event_menuCadasProdutoActionPerformed

    private void menuConsulProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsulProdutoActionPerformed
        if (consultarProduto == null || !consultarProduto.isDisplayable()) {
            consultarProduto = new ConsultaProdutoUI(false);
            consultarProduto.pack();
            consultarProduto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            consultarProduto.setLocationRelativeTo(null);
            consultarProduto.setVisible(true);
        }
        consultarProduto.toFront();
    }//GEN-LAST:event_menuConsulProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalUI().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem menuCadasCliente;
    private javax.swing.JMenuItem menuCadasProduto;
    private javax.swing.JMenuItem menuConsulCliente;
    private javax.swing.JMenuItem menuConsulProduto;
    // End of variables declaration//GEN-END:variables
}
